name: angular_tour_of_heroes
description: Tour of Heroes
version: 0.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  ngdart: ^7.0.2

# #docregion dev_dependencies, build-dependencies
dev_dependencies:
  # #enddocregion build-dependencies
  ngtest: ^4.0.1
  # #docregion build-dependencies
  build_runner: ^2.1.7
  build_test: ^2.1.5
  build_web_compilers: ^3.2.2
  # #enddocregion build-dependencies
  test: ^1.20.1
# #enddocregion dev_dependencies
